#!/usr/bin/python3
import re
# Read in entire dictionary
with open("/usr/share/dict/words") as f:
    w=f.readlines()

r1 = [m.string for l in w for m in [re.search(r'^[^A-Zdstengy]{5}$', l.strip())] if m]
r2 = [m.string for l in r1 for m in [re.search(r'(?=.*a)(?=.*i)(?=.*l)', l.strip())] if m]

[print(m.string) for l in r2 for m in [re.search(r'.[^i].[^a][^l]', l.strip())] if m]
