#!/usr/bin/python3

# Need to install python3-pyqt5.qtx11extras
import sys
from PyQt5.QtGui import  *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtX11Extras import *

class XMagQLabel(QLabel):
	def setLabel(self, label):
		self.label=label

	def setqimage(self, qimage):
		self.qimage=qimage

	def mouseMoveEvent(self, event):
		# Check bounds
		if event.x()>=self.qimage.width():
			return
		if event.y()>=self.qimage.height():
			return
		if event.x()<0:
			return
		if event.y()<0:
			return
		c=self.qimage.pixelColor(event.pos())
		t="Color [{x:3d},{y:3d}] ({r:2X},{g:2X},{b:2X},{a:2X})".format(x=event.x(),y=event.y(),r=c.red(),g=c.green(),b=c.blue(),a=c.alpha())
		self.label.setText(t)

class XMagQWidget(QWidget):
	replace=False

	def setParent(self,parent):
		self.parent=parent

	def mouseReleaseEvent(self,event):
		if self.replace==False:
			return
		self.replace=False
		self.releaseMouse()
		self.parent.update(event.globalPos())

	def update(self,tf):
		self.replace=tf

class pyqtmag:
	def __init__(self):
		# Create the window and set the size/position/title appropriately
		self.app=QApplication(sys.argv)
		self.w=XMagQWidget()
		self.w.setGeometry(100,100,200,200)
		self.w.setWindowTitle('PyQtMag')
		self.screen=self.app.primaryScreen()

		# Add a grid-style layout for the widgets
		self.layout=QGridLayout()
		self.w.setLayout(self.layout)

		# Add a button to replace the grabbed image
		self.replace=QPushButton("Replace")
		self.replace.clicked.connect(self.replace_cb)
		self.layout.addWidget(self.replace,1,1,1,1)

		# Add a widget to show the captured image
		self.label=XMagQLabel()
		self.qimage=QImage()
		self.layout.addWidget(self.label,2,1,1,2)
		self.label.setqimage(self.qimage)

		# A widget to show the color of a pixel in the image
		self.info=QLabel("Color")
		self.layout.addWidget(self.info,3,1,1,2)
		self.label.setLabel(self.info)


		# Add a quit button to the gui
		self.quit=QPushButton("Quit")
		self.quit.clicked.connect(self.quit_cb)
		self.layout.addWidget(self.quit,4,2,1,1)

		# Add an option to save the grabbed image
		self.save = QPushButton("Save")
		self.save.clicked.connect(self.save_img)
		self.layout.addWidget(self.save,4,1,1,1)

		# Show the window
		self.rootwindow=QX11Info.appRootWindow()
		self.w.show()
		self.window=self.app.allWindows()
		self.w.setParent(self)

	def start(self):
		self.app.exec_()

	def quit_cb(self):
		quit()

	def replace_cb(self):
		# Allow mouse to move around to grab a spot
		pm=QPixmap('cursor.png')
		cursor=QCursor(pm,hotX=0,hotY=0)
		self.w.grabMouse(cursor)
		self.w.update(True)

	# Save the captured (unscaled) image to a file
	def save_img(self):
		# Open a save file dialogue for the user
		name,_ = QFileDialog.getSaveFileName(None, 'Save file', 'screenshot.png', '*.png')

		if (name): # do nothing if no name was selected (dialog closed?)
			# Attempt to save the file
			try:
				self.pixmap.save(name, 'PNG')
				print('Saved file as:', name)
			except Exception as e:
				print(e, file = sys.stderr)


	def update(self,pos):
		# Grab a 50x50 pixel image at the cursor location (cursor at top left corner)
		self.pixmap=self.screen.grabWindow(self.rootwindow,pos.x(),pos.y(),50,50)

		# Scale the image up to 200x200 for displaying (pyqt**MAG**)
		self.size=QSize(200,200)
		self.pixmap_scaled=self.pixmap.scaled(self.size)
		self.qimage=self.pixmap_scaled.toImage()

		# Show the scaled image
		self.label.setPixmap(self.pixmap_scaled)
		self.label.setqimage(self.qimage)

if __name__=='__main__':
	app=pyqtmag()
	app.start()

